### ISSUE TITLE
Permission Request!

### ISSUE THREAD

**Issue by Voidrainbows** [Taranchuk/EncounterFramework#1]
Sorry not a real issue, but this is a great Framework!
I was wondering if I could use it in my Rimworld mod?

**Comment by Taranchuk** [comment]
Hello. You have my permission. Just place the dll file in Assemblies folder. Let me know if you will have any issues with it, will try to get them fixed in my free time

**Comment by Voidrainbows** [comment]
Alrights! Thanks so much!

**Comment by Voidrainbows** [comment]
Oh right I wanted to know how you made the Preset map files? I see that the file is split into several sections (buildings, items etc) but rimworld save files don't save like that. So I am wondering how you generate a map file.

**Comment by Taranchuk** [comment]
You need to go to dev actions button (top button when dev mode is enabled) and search for "blueprint" actions. One of them will do the job.

**Comment by Taranchuk** [comment]
After that search for the created preset file and move it to your mod folder as you want and then make LocationDef for it

**Comment by Voidrainbows** [comment]
Ah I see! Thanks so much

**Comment by Voidrainbows** [comment]
Question about the ThreatGenerator. Do storyteller's use it automatically, if not how are they activated?

**Comment by Taranchuk** [comment]
threat generators are defined in location defs. Upon location creation threats will be generated accordingly to them
Example of usage

	<EncounterFramework.LocationDef>
		<defName>RH_PlanetaryKillerSite</defName>
		<filePreset>Presets/RH_VOID/Sites/PlanetaryKillerSite.xml</filePreset>
		<seedGeneration>398138181</seedGeneration>
		<mapSize>(250, 1, 250)</mapSize>
		<threatGenerator>
			<options>
				<li>
					<lordJobType>Verse.AI.Group.LordJob_DefendPoint</lordJobType>
					<indoorsOnly>true</indoorsOnly>
					<defaultFaction>RH_VOID</defaultFaction>
					<pawnsToSpawn>
						<RH_VOID_Undying>4</RH_VOID_Undying>
						<RH_BlackTitan>1</RH_BlackTitan>
					</pawnsToSpawn>
				</li>
			</options>
		</threatGenerator>
	</EncounterFramework.LocationDef>

**Comment by Voidrainbows** [comment]
Ah so you can't do it for raids? I was wondering how to trigger incidents when raids occured.

**Comment by Taranchuk** [comment]
Well this is a mod about creating locations, so no. There might be something about raid reinforcements though, but that's all

**Comment by Voidrainbows** [comment]
ah ok. thanks once again!
